blank_issues_enabled: false
contact_links:
  - name: Super Mario Odyssey Modding Discord
    url: https://discord.gg/FDJXvY4awU
    about: Simple questions can be answered in the offical SMO Modding Discord!
