using System;
using System.IO;
using System.Collections.Generic;
using Godot;

using CommunityToolkit.HighPerformance;

namespace Nindot.LMS.Msbt.TagLib.Smo;

public class MsbtTagElementProjectIcon : MsbtTagElement
{
    public TagNameProjectIcon Icon
    {
        get { return (TagNameProjectIcon)TagName; }
        set
        {
            if (!Enum.IsDefined(typeof(TagNameProjectIcon), value))
            {
                GD.PushWarning("Attempted to set ProjectIcon Tag IconType to invalid type");
                TagName = (ushort)TagNameProjectIcon.PadStyleButtonA;
                UpdateIconTableByTag();
                return;
            }

            TagName = (ushort)value;
            UpdateIconTableByTag();
        }
    }

    private List<string> _iconTable = [];

    public MsbtTagElementProjectIcon(ref int pointer, byte[] buffer) : base(ref pointer, buffer)
    {
        // Assign Icon to TagName to run update function
        // The buffer contains the IconTable, however the information in that table can be
        // entirely inferred from the TagName. To simplfy the read/edit/write on this tag,
        // the IconTable will be generated by the update function instead of the buffer.
        Icon = (TagNameProjectIcon)TagName;

        // Ensure DataSize property is up-to-date after generating table
        DataSize = CalcDataSize();
        return;
    }

    public ushort CalcDataSize()
    {
        ushort value = 0;

        foreach (string icon in _iconTable)
        {
            int strLen = icon.ToUtf16Buffer().Length;
            value += (ushort)(strLen + 2);
        }

        return value;
    }

    public void SetIcon(TagNameProjectIcon icon)
    {
        Icon = icon;
        UpdateIconTableByTag();
    }

    public override byte[] GetBytes()
    {
        // Ensure DataSize is up-to-date with table strings
        DataSize = CalcDataSize();

        // Now that data size is correct, stream can be created
        MemoryStream value = CreateMemoryStreamWithHeaderData();

        foreach (string icon in _iconTable)
        {
            byte[] buf = icon.ToUtf16Buffer();
            ushort strLen = (ushort)buf.Length;

            value.Write(strLen);
            value.Write(buf);
        }

        return value.ToArray();
    }

    public override bool IsFixedDataSize()
    {
        return false;
    }

    public override string GetTagNameStr()
    {
        if (Enum.IsDefined(typeof(TagNameProjectIcon), TagName))
            return Enum.GetName(typeof(TagNameProjectIcon), TagName);

        return "Unknown";
    }

    private void UpdateIconTableByTag()
    {
        var tagName = GetTagNameStr();
        if (tagName == null || tagName == "Unknown")
            return;
        
        switch (tagName)
        {
            case "ShineIconCurrentWorld" or "CoinCollectIconCurrentWorld":
                _iconTable.Clear(); // These two tags do not use the icon table
                break;
            case string s when s.StartsWith("PadStyle"):
                UpdateIconTableForPadStyle(tagName);
                break;
            case string s when s.StartsWith("PadPair"):
                UpdateIconTableForPadPair(tagName);
                break;
            default:
                GD.PushWarning("Cannot update IconTable for invalid TagName!");
                break;
        }

        DataSize = CalcDataSize();
    }

    private void UpdateIconTableForPadStyle(string tagName)
    {
        var suffix = tagName.Replace("PadStyle", "");

        _iconTable.Clear();
        foreach (var prefix in _padStylePrefixes)
        {
            _iconTable.Add(prefix + suffix);
        }
    }

    private void UpdateIconTableForPadPair(string tagName)
    {
        var prefix = tagName.Replace("PadPair", "");

        _iconTable.Clear();
        foreach (var suffix in _padPairSuffixes)
        {
            _iconTable.Add(prefix + suffix);
        }
    }

    private static readonly string[] _padStylePrefixes = [
        "Dual",
        "Handheld",
        "FullKey",
        "Left",
        "Right",
    ];

    private static readonly string[] _padPairSuffixes = [
        "Button",
        "PlayerL",
        "PlayerR",
    ];
};