<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <PackageVersion>1.0.0</PackageVersion>
    <PackageProjectUrl>https://github.com/Amethyst-szs/MoonFlow</PackageProjectUrl>
    <NoWarn>IDE0130,IDE0160</NoWarn> <!-- Disable namespace folder structure matching -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Module\AuroraLib.Compression\src\AuroraLib.Compression\AuroraLib.Compression.csproj" />
    <ProjectReference Include="..\Module\SarcLibrary\src\SarcLibrary\SarcLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nindot.BymlLibrary" Version="1.0.5" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>